<?php

/**
 * @file
 * Module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node_orders\Controller\Group;

/**
 * Node_orders_entity_presave.
 */
function node_orders_entity_presave(EntityInterface $node) {
  if (method_exists($node, 'getType') && $node->getType() == 'orders') {
    $usluga = ' --- ';
    if (is_object($node->field_orders_ref_activity->entity)) {
      $usluga = $node->field_orders_ref_activity->entity->title->value;
    }
    $title = 'Заявка на ' . $usluga . ' от ' . format_date(time(), 'long');
    $node->title->setValue($title);
  }
}

/**
 * Node_orders_entity_view.
 */
function node_orders_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if (method_exists($entity, 'getType') && $entity->getType() == 'orders') {
    $group = Group::groupCounter($entity);
    $count = Group::ordersCalc($entity);
    $build['group_view'] = [
      '#markup' => 'Численность группы (все люди): ' . $group . ' чел.',
    ];
    $entity->field_orders_group->setValue($group);
    $entity->field_orders_cost_raschet->setValue($count);
    $entity->save(TRUE);
  }
}
